# Generated by Django 3.1.2 on 2021-03-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_tag',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
    ]
